version: "3.8"
services:
  backend:
    restart: always
    build: ./backend
    depends_on:
      - db
    networks:
      - dist
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/dist
  db:
    image: postgres:15
    restart: always
    networks:
      - dist
    environment:
      POSTGRES_DB: dist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  dist:
    driver: bridge
volumes:
  postgres-data:
