version: "3.8"
services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://basen:zaXJeROoT8mVS3Z8JMU1CgiAvOfDpXw9@dpg-crs0ikogph6c738n6jag-a.oregon-postgres.render.com/db_x82y
